apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventapp-be-${COLOR}
  namespace: eventapp-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eventapp-be
      version: ${COLOR}
  template:
    metadata:
      labels:
        app: eventapp-be
        version: ${COLOR}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: backend
          image: nschiau/eventapp:${BUILD_TAG} # pulled from Docker Hub
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://0.0.0.0:8080"
            - name: ConnectionStrings__DefaultConnection
              value: "Host=eventapp-db;Database=eventhorizon;Username=postgres;Password=postgres"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
