apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventapp-fe-${COLOR}
  namespace: eventapp-prod
  labels:
    app: eventapp-fe
    version: ${COLOR}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eventapp-fe
      version: ${COLOR}
  template:
    metadata:
      labels:
        app: eventapp-fe
        version: ${COLOR}
    spec:
      imagePullSecrets:
        - name: regcred # Docker Hub secret for pulling images
      containers:
        - name: frontend
          image: nschiau/eventapp:${BUILD_TAG}
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_BASE_URL
