apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eventapp-ingress-fe
  namespace: eventapp-prod
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: eventapp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eventapp-fe-svc
                port:
                  number: 80
