apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eventapp-ingress
  namespace: eventapp-prod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: eventapp.local
      http:
        paths:
          # Backend — match /api/... and strip /api
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: eventapp-be-svc
                port:
                  number: 80

          # Frontend — match everything else (no rewrite)
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: eventapp-fe-svc
                port:
                  number: 80
