apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eventapp-ingress
  namespace: eventapp-prod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: eventapp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eventapp-fe-svc
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: eventapp-be-svc
                port:
                  number: 80
