apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eventapp-ingress
  namespace: eventapp-prod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: eventapp.local
      http:
        paths:
          # Backend — routes /api and subpaths
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: eventapp-be-svc
                port:
                  number: 80

          # Frontend — routes everything else
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eventapp-fe-svc
                port:
                  number: 80
