apiVersion: v1
kind: Service
metadata:
  name: eventapp-db
  namespace: eventapp-prod
spec:
  clusterIP: None # headless service for direct Pod discovery
  selector:
    app: eventapp-db
  ports:
    - port: 5432
      targetPort: 5432
